name = "Actions & Better [ON JAVA]"
author = "zdkrr"
version = "2.5-26.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9936180ef563125bb63a5c329f1476a75ca5e037fb01bc3a597f551504eba5ba"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
