name = "Actions & Better [ON JAVA]"
author = "zdkrr"
version = "2.5-26.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b1cf22d94e63a71622f3013c7c3c6afe84daa46c30452a8f855b64be3655990a"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
