name = "Actions & Better [ON JAVA]"
author = "zdkrr"
version = "2.5-26.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "99dea218c452b4f890ff4fd29c971fe1429957f14d396777ef11ea47a5bfbf76"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
