lasso:
  lassoDurability:
    #The durability of the lasso.
    #Minimum value: 1, Maximum value: 2147483647, Default value: 256
    256
  allowLassoLooting:
    #Whether looting works on generated loot.
    #Default value: true
    true
farms:
  wood:
    speed:
      #Minimum value: 0.001, Maximum value: 1.7976931348623157E308, Default value: 50.0
      50.0
    enabled:
      #Default value: true
      true
    allows_hostile:
      #Default value: false
      false
  stone:
    speed:
      #Minimum value: 0.001, Maximum value: 1.7976931348623157E308, Default value: 40.0
      40.0
    enabled:
      #Default value: true
      true
    allows_hostile:
      #Default value: false
      false
  iron:
    speed:
      #Minimum value: 0.001, Maximum value: 1.7976931348623157E308, Default value: 30.0
      30.0
    enabled:
      #Default value: true
      true
    allows_hostile:
      #Default value: true
      true
  gold:
    speed:
      #Minimum value: 0.001, Maximum value: 1.7976931348623157E308, Default value: 20.0
      20.0
    enabled:
      #Default value: true
      true
    allows_hostile:
      #Default value: true
      true
  diamond:
    speed:
      #Minimum value: 0.001, Maximum value: 1.7976931348623157E308, Default value: 10.0
      10.0
    enabled:
      #Default value: true
      true
    allows_hostile:
      #Default value: true
      true
  emerald:
    speed:
      #Minimum value: 0.001, Maximum value: 1.7976931348623157E308, Default value: 5.0
      5.0
    enabled:
      #Default value: true
      true
    allows_hostile:
      #Default value: true
      true
  inferno:
    speed:
      #Minimum value: 0.001, Maximum value: 1.7976931348623157E308, Default value: 2.5
      2.5
    enabled:
      #Default value: true
      true
    allows_hostile:
      #Default value: true
      true
  ultimate:
    speed:
      #Minimum value: 0.001, Maximum value: 1.7976931348623157E308, Default value: 0.5
      0.5
    enabled:
      #Default value: true
      true
    allows_hostile:
      #Default value: true
      true
blacklist:
  blacklisted_mobs:
    #A list of mob IDs that cannot be captured by lassos.
    #Default value: ['minecraft:ender_dragon', 'minecraft:wither', 'minecraft:warden']
    - minecraft:ender_dragon
    - minecraft:wither
    - minecraft:warden
