#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Aug 18 20:37:05 GMT+07:00 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=8
shaderPack=ComplementaryReimagined_r5.8.1 + EuphoriaPatches_1.9.3
